# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Authors',   url: 'authors.html'}
- {name: 'Slides',   url: '#slides'}
- {name: 'Notebooks',   url: '#notebooks'}
- {name: 'Program',   url: 'program.html'}
- {name: 'Bibliography',   url: 'biblio.html'}
- {name: 'NeurIPS 2024',   link: 'https://neurips.cc/virtual/2024/tutorial/99527'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'github',     link: 'https://www.github.com/lenpaul'}
# - {icon: 'twitter',    link: 'https://twitter.com/paululele'}
# - {icon: 'linkedin',   link: 'http://www.linkedin.com/in/lenpaul/'}
# - {icon: 'envelope',   link: 'mailto:l.nguyen.paul@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Previous'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
